debug: debug                          #开发者模式
httpRequestPort: :8089                #HTTP请求端口
appSecret :
sessionName :
databases:
  type: mysql                         #数据库类型
  hostName:                           #服务器地址
  port:                               #数据库端口
  userName:                           #用户名
  dbName:                             #数据库名
  password:                           #密码
  prefix:                             #数据库表前缀
cache:
  type: redis
  port: 6379
  host: 127.0.0.1
  password:

