debug: debug                          #开发者模式
httpRequestPort: :8089               #HTTP请求端口
appSecret : ssc
sessionName : shangce_sesssion
databases:
  type: mysql                        #数据库类型
  hostName: 192.168.199.231          #服务器地址
  port: 3306                         #数据库端口
  userName: root                     #用户名
  dbName: abs_db_20190117            #数据库名
  password: 123456                   #密码
  prefix: ssc_                       #数据库表前缀
cache:
  type: redis
  port: 6379
  host: 127.0.0.1
  password:

